version: "3.5"

services:
  app:
    container_name: gacha-api_app
    image: gacha-api/app
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    env_file:
      - .env
    networks: 
      - container-link
  db:
    container_name: gacha-api_db
    image: gacha-api/db
    build:
      context: database
      dockerfile: ./Dockerfile
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.conf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init_db:/docker-entrypoint-initdb.d
      - ./mysql/access.conf:/home/access.cnf
    env_file:
      - .env.db
    networks: 
      - container-link

networks:
  default:
    external:
      name: bridge
  container-link:
    name: gacha-api_link
      