name: Go

on:
  push:
    branches:
      - "master"
      - "develop"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  pull_request:
    branches:
      - "master"
      - "develop"
      - "feature/**"
      - "hotfix/**"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
